redhat-cop/helm-charts

- jenkins/templates/deploymentconfig.yaml
- jenkins/templates/rolebinding.yaml
- jenkins/templates/route.yaml
- jenkins/templates/serviceaccount.yaml
- jenkins/values.yaml
tested against openshift 4.3, argocd 1.5.0-rc1
> fix up quoting and typos

- jenkins/templates/imagestream.yaml
only need imagestream.yaml OR external-jenkins-imagestream.yaml to define jenkins:latest
> 🦪 we only need one image stream, conditional 🦪

- .gitignore
- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/requirements.yaml
- charts/sonarqube/templates/_helpers.tpl
- charts/sonarqube/templates/config.yaml
- charts/sonarqube/templates/copy-plugins.yaml
- charts/sonarqube/templates/deployment.yaml
- charts/sonarqube/templates/ingress.yaml
- charts/sonarqube/templates/install-plugins.yaml
- charts/sonarqube/templates/postgres-dc.yaml
- charts/sonarqube/templates/postgres-service.yaml
- charts/sonarqube/templates/pvc.yaml
- charts/sonarqube/templates/route.yaml
- charts/sonarqube/templates/secret.yaml
- charts/sonarqube/templates/service.yaml
- charts/sonarqube/templates/serviceaccount.yaml
- charts/sonarqube/values.yaml
> 🍿 sonarqube chart 🍿

- charts/bootstrap-project/values.yaml
> 🧪 teh != the 🧪

- charts/bootstrap-project/templates/bindings.yaml
- charts/bootstrap-project/templates/namespace.yaml
- charts/bootstrap-project/templates/serviceaccount.yaml
- charts/bootstrap-project/values.yaml
do not merge yet
alternative namespace global values
matches with - https://github.com/rht-labs/ubiquitous-journey/compare/master...eformat:feature/namespace-globals?expand=1
> 🍿 WIP - Feature/namespace globals 🍿

- charts/operatorhub/Chart.yaml
- charts/operatorhub/README.md
An operatorhub helm chart doc. added due to the issue: #13
> add operatorhub helm chart doc

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
switch to rht cop dex image
see - https://github.com/rht-labs/ubiquitous-journey/pull/125
> ♻️ Fix/dex ♻️

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/argocd-operator/templates/Secret.yaml
- charts/argocd-operator/values.yaml
Secret template is added to use for private repos with ArgoCD
> ♌ privaterepo config added ♌

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/PrometheusSubscription.yaml
add prometheus operator subscription back when metrics enabled
was accidentally removed here:
https://github.com/rht-labs/ubiquitous-journey/pull/122
> 🦜 Fix/prometheus 🦜

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/PrometheusSubscription.yaml
prometheus is namesapces .. didnt notice this until did master -> child deploy !
> 🦚 namespaced prom 🦚

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/OperatorGroup.yaml
- charts/argocd-operator/templates/Subscription.yaml
- charts/argocd-operator/values.yaml
Fixes: https://github.com/rht-labs/helm-charts/issues/42
CC @springdo
> 🥰 Added option to enable operator and operatorgroup for argocd-operator 🥰

- charts/operatorhub/Chart.yaml
- charts/operatorhub/templates/operatorgroup.yaml
Fixes: https://github.com/rht-labs/helm-charts/issues/23
> 😃Added logic to check if create exists on operatorgroup for operator chart 😃

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/bootstrap-project/Chart.yaml
fixes: https://github.com/rht-labs/helm-charts/issues/41
i have retested with our latest versions. LGTM.
> 🦘Fix/dex 🦘

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/argocd-operator/values.yaml
@ckavili if you have a sec - this is going to be used for token generation
> 🏗  ADD - accounts for argocd for token gener 🏗

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
> 🦆 Feature/argocd version 🦆

- README.md
- charts/sealed-secrets/.helmignore
- charts/sealed-secrets/Chart.yaml
- charts/sealed-secrets/OWNERS
- charts/sealed-secrets/README.md
- charts/sealed-secrets/ci/ci-values.yaml
- charts/sealed-secrets/templates/NOTES.txt
- charts/sealed-secrets/templates/_helpers.tpl
- charts/sealed-secrets/templates/cluster-role-binding.yaml
- charts/sealed-secrets/templates/cluster-role.yaml
- charts/sealed-secrets/templates/deployment.yaml
- charts/sealed-secrets/templates/ingress.yaml
- charts/sealed-secrets/templates/networkpolicy.yaml
- charts/sealed-secrets/templates/psp-clusterrole.yaml
- charts/sealed-secrets/templates/psp-clusterrolebinding.yaml
- charts/sealed-secrets/templates/psp.yaml
- charts/sealed-secrets/templates/role-binding.yaml
- charts/sealed-secrets/templates/role.yaml
- charts/sealed-secrets/templates/sealedsecret-crd.yaml
- charts/sealed-secrets/templates/service-account.yaml
- charts/sealed-secrets/templates/service.yaml
- charts/sealed-secrets/values.yaml
Adds sealed secrets chart from a personal repo, until changes are merged upstream.
This chart support the namespace var, so we can use it during the bootstrap process.
> Adds sealed-secrets

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
> 🦩argocd-1.6.0 🦩

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/argocd-operator/values.yaml
> 🦘 latest argocd 1.6.1, operator 0.0.11 🦘

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
update to latest patched ubi nexus image
> 🦑 latest sontaype ubi image 🦑

- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
@ckavili  - if you have 2 sec .....
> 🦦 Version bumps for new s2i 🦄🔥

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/deploymentconfig.yaml
This fixes the issue where the resources.limits.memory value was incorrect
> Fix for Issue #71

- README.md
@sabre1041 - as per the chat. This needs changing to reflect the org change
> 🙈 FIX - repository namespace changes for CoP Org 🙊

- index.html
@sabre1041 - another one for you since migrating repos
> 🐭 FIX - New org names etc 🏰

- README.md
> 🐯 FIX - broken readme link 🐯

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
looks like the latest prometheus operator now in catalog. bump to support this version
> 🐻‍❄️bump prom operator version to latest 🐻‍❄️

- .github/workflows/conftest.yaml
- .gitignore
- _test/bats-support-clone.bash
- _test/conftest.sh
Do you know what this repo is missing? some conftest, OBVS!
Only checks for deprecated APIs currently. Raised https://github.com/redhat-cop/helm-charts/issues/82 to discuss what should be fixed/turned on.
> Added conftest to ci

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
security patch fixes, update to latest nexus image
> 🦏 updated nexus to latest 3.27 image 🦏

- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/values.yaml
Cleaned up some legacy language around Jenkins agents and added three additional ones. I also like things in alphabetical order :capital_abcd:
> Jenkins agents rename + erlang,graalvm & rust agents 🔠

- charts-we-like.md
> 🕵️‍♂️ Add reference to Sealed Secrets in Charts we Like 🕵️‍♀️

- README.md
Found a bunch of charts which are probs useful, not sure if they really do belong here but we should at least reference them. 
https://github.com/redhat-cop/openshift-management/issues/75
@ckavili - if you have 2 sec to mergé 
😋
> 🐯 UPDATE - Add link to other helm charts I found in CoP this morning 🦁

- charts/network-policy/.helmignore
- charts/network-policy/Chart.yaml
- charts/network-policy/README.md
- charts/network-policy/templates/NetworkPolicy.yaml
- charts/network-policy/templates/_helpers.tpl
- charts/network-policy/values.yaml
FYI - work from today's sesh ....   
@rh-jpoole @ckavili
> 🌐📝 - ADD Network policy chart

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/postgres-dc.yaml
- charts/sonarqube/templates/postgres-pvc.yaml
- charts/sonarqube/templates/postgres-secret.yaml
- charts/sonarqube/templates/postgres-service.yaml
- charts/sonarqube/templates/sonar-cm-config.yaml
- charts/sonarqube/templates/sonar-cm-copy-plugins.yaml
- charts/sonarqube/templates/sonar-cm-install-plugins.yaml
- charts/sonarqube/templates/sonar-deployment.yaml
- charts/sonarqube/templates/sonar-ingress.yaml
- charts/sonarqube/templates/sonar-pvc.yaml
- charts/sonarqube/templates/sonar-route.yaml
- charts/sonarqube/templates/sonar-service.yaml
- charts/sonarqube/templates/sonar-serviceaccount.yaml
Sonarqube helm templates produce incorrect resources in argocd. 
Remove and tidy whitespace generated by templates.
> 🧬 Fix/sonarqube chart templates 🧬

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
Added initialSSHKnownHosts option as described here: https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#initial-ssh-known-hosts
Example object: 
```
initialSSHKnownHosts:
- "[gitlab.internal.example.com]:2222,[200.12.12.200]:2222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYADDBAABgmILCwFe3UY5XyVJplRDSSrLCA9ji5KzNo/2K0DKwWBLcLvoyUVee1dCphUugT7c8Jk+EllQD11hMk4dn7AbF="
- "bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9 …
```
> Add initial known hosts

- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
openshift 4.6 istag chnaged for postgresql
```
oc get is postgresql -n openshift -o yaml
tag: 9.6-el8
```
> 🐦 postgres image tag changed 🐦

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/values.yaml
Updated to latest ubi image, tested OK:
sonatype-nexus-1608090002-6fc45c9bf8-sjf9r nexus -------------------------------------------------
sonatype-nexus-1608090002-6fc45c9bf8-sjf9r nexus 
sonatype-nexus-1608090002-6fc45c9bf8-sjf9r nexus Started Sonatype Nexus OSS 3.29.0-02
sonatype-nexus-1608090002-6fc45c9bf8-sjf9r nexus 
sonatype-nexus-1608090002-6fc45c9bf8-sjf9r nexus -------------------------------------------------
> 🦩 Feature/nexus 3.29 🦩

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
update to latest argocd 1.8.2
tested against UbiquitousJourney labs ci-cd
> 🦢 Feature/argocd 1.8.2 🦢

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
> 🐤 Feature/nexus 3.29.1 🐤

- charts/pact-broker/Chart.yaml
- charts/pact-broker/values.yaml
Postgres image version updated with the min version at Opensift 4.6
> 📺 postgres version updated 📺

- charts/helper-console-links/Chart.yaml
- charts/helper-console-links/templates/ConsoleLink.yaml
- charts/helper-console-links/values.yaml
support section lists for helper chart
> 🦆 Console links support lists 🦆

- charts/argocd-operator/Chart.yaml
- charts/bootstrap-project/Chart.yaml
- charts/dev-ex-dashboard/Chart.yaml
- charts/etherpad/Chart.yaml
- charts/helper-console-links/Chart.yaml
- charts/helper-sealed-secrets/Chart.yaml
- charts/jenkins/Chart.yaml
- charts/network-policy/Chart.yaml
- charts/operatorhub/Chart.yaml
- charts/owncloud/Chart.yaml
- charts/pact-broker/Chart.yaml
- charts/sonarqube/Chart.yaml
- charts/sonarqube/requirements.yaml
- charts/sonatype-nexus/Chart.yaml
- charts/static-site/Chart.yaml
Added icon for helm charts
Fixes https://github.com/redhat-cop/helm-charts/issues/102
> 🐬 icon added for helm charts 🐬

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
> 🐝 argocd 1.8.3 🐝

- charts/ploigos/Chart.yaml
- charts/ploigos/values.yaml
> 🦩 ploigos 0.2.2 🦩

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
> 🐞 bump argcod 1.8.5 🐞

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
> 🐈‍⬛ argocd 1.8.7 🐈‍⬛

- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
@eformat  if you have 2 sec ....
> 🐦 BUMP bc for s2i to latest to prevent massive overrides 🐦

- charts-we-like.md
> 🐇 fix typo in README 🐇

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/buildconfigs.yaml
- charts/jenkins/templates/imagestreams.yaml
- charts/jenkins/values.yaml
@ckavili or @eformat if either of you gets a moment to smash this one in it would be great! 🌵
> 🐩 FIX - unnecessary secret and simplify the buildconfigs 🐩

- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
- update to latest sonarqube 8.7.1-community
- update postgresql:12-el8
older versions starting to give errors on startup
```
2021.03.21 01:00:16 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.NullPointerException: null
at org.sonar.server.es.metadata.MetadataIndexImpl.getMetadata(MetadataIndexImpl.java:98)
at org.sonar.server.es.metadata.MetadataIndexImpl.getDbVendor(MetadataIndexImpl.java:84)
at org.sonar.server.es.metadata.EsDbCompatibilityImpl.hasSameDbVendor(EsDbCompatibilityImpl.java:37)
at org.sonar.server.es.IndexCreator.checkDbCompatibility(IndexCreator.java:203)
```
> 🦋 updated to newer versions 🦋

- _test/conftest.sh
as per $subject - few charts have be contributed lately which have missed being added to conftest
> added new charts to conftest

- .github/PULL_REQUEST_TEMPLATE.md
everyone loves a good GH template!
FYI: there isn't a group for helm-charts, so left it as day-in-life, which i think 90% of mergers are on.
> added gh template for PRs

- charts/ploigos/Chart.yaml
- charts/ploigos/values.yaml
update to newest ploigos version.. looks like older versions not in operator catalog
> 🦩newest version 🦩

- charts-we-like.md
> re-wording / grammar fixes to charts-we-like

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
update nexus image to latest
this PR also includes PR https://github.com/redhat-cop/helm-charts/pull/144
```
oc new-project nexus-test
helm template foo . | oc apply -f-
```
test output
```
foo-sonatype-nexus-6499f98b7d-2g7jk nexus -------------------------------------------------
foo-sonatype-nexus-6499f98b7d-2g7jk nexus 
foo-sonatype-nexus-6499f98b7d-2g7jk nexus Started Sonatype Nexus OSS 3.30.0-01
foo-sonatype-nexus-6499f98b7d-2g7jk nexus 
foo-sonatype-nexus-6499f98b7d-2g7jk nexus -------------------------------------------------
virt:~/$ stern nexus-setup-npbfr
+ nexus-setup-npbfr › nc
nexus-setup-npbfr nc /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
nexus-setup-npbfr nc waiting for nexus pod ready...
nexus-setup-npbfr nc …
```
> Feature/nexus 3.30.0 ubi 1

- charts/argocd-operator/Chart.yaml
- charts/bootstrap-project/Chart.yaml
- charts/dev-ex-dashboard/Chart.yaml
- charts/etherpad/Chart.yaml
- charts/helper-console-links/Chart.yaml
- charts/jenkins/Chart.yaml
- charts/network-policy/Chart.yaml
- charts/pact-broker/Chart.yaml
- charts/ploigos/Chart.yaml
- charts/sonarqube/Chart.yaml
- charts/sonatype-nexus/Chart.yaml
release on master has been failing. this fixes it.
cause: always bump versions if ANYTHING has changed in the charts dir:
- https://github.com/redhat-cop/helm-charts/pull/137
as we didn't bump the versions for the above PR, the release thought something had changed for those charts so kept trying to release the same version.
- https://github.com/garethahealy/helm-charts/actions/runs/745967006 : release of this PR
- https://github.com/garethahealy/helm-charts/actions/runs/745971527 : release still working if something random commited
> bumped versions to fix release

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
> Add new repos to Nexus

- charts/etherpad/Chart.yaml
- charts/etherpad/templates/deployment.yaml
- charts/etherpad/values.yaml
See related issue
Fixes #155 
helm package etherpad
values.yaml:
```
image:
tag: 1.8.13
```
helm install -f value-pad.yml -n etherpad etherpad etherpad-0.0.6.tgz
> Feature/etherpad: make name/tag configurable

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/Secret.yaml
Git Auth secret was created on which namespace we run helm command, not in the namespace specified in values. Updated secret template to fix that.
> 🐣 ns added to secret 🐣

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ClusterRoleBinding.yaml
- charts/argocd-operator/templates/RoleBinding.yaml
- charts/argocd-operator/templates/wait-for-crd.yaml
- charts/argocd-operator/values.yaml
new argocd operator that support v2.x of argocd released
see test
> 🪲 update for argocd 2.0.2 and operator 0.0.15 🪲

- charts/operatorhub/Chart.yaml
- charts/operatorhub/templates/subscription.yaml
PR to fix the channel bot being a string..... eg for openshift-logging operator the channel is `4.6` or `5.0`
> 🦆 FIX - subscription breaks if channel is number 🦆

- .github/workflows/lint-test.yaml
Linting action fails with the following error but not fails the action itself. It looks like `ubuntu-latest` ships with Python 3.8 which causes the issue so it is recommended to fix the python version to v3.7.0.
```
Warning: Unexpected input(s) 'command', 'config', valid inputs are ['version']
Run helm/chart-testing-action@v2.1.0
Installing chart-testing...
Creating virtual Python environment...
Activating virtual environment...
Installing yamllint...
Collecting yamllint==1.25.0
Downloading yamllint-1.25.0-py2.py3-none-any.whl (60 kB)
Requirement already satisfied: setuptools in /opt/hostedtoolcache/ct/v3.4.0/x86_64/venv/lib/python3.8/site-packages (from yamllint==1.25.0) (44.0.0)
Collecting pyyaml
Downloading PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting …
```
> Helm lint action updated 🔥

- .github/workflows/lint-test.yaml
- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/anyuid-scc.yaml
> ClusterRoleBinding updated for Argo Redis

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/deploymentconfig.yaml
- charts/jenkins/templates/rolebinding.yaml
Small fixe to the Jenkins chart 
> 🐡 FIX - linting and image pull policy 🐡

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
> 🌶️ argocd 2.0.5 🌶️

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/deploymentconfig.yaml
- charts/jenkins/templates/rolebinding.yaml
- charts/jenkins/values.yaml
Quick tidy up of Jenkins chart for DO500 simples
> 🦆 UPDATE - helm chart to keep more sensible defaults 🦆

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
I forgot to bump the appVersion in https://github.com/redhat-cop/helm-charts/pull/177
should be 2.0.5
> 🐞 forgot to bump appVersion 🐞

- charts/argocd-operator/values.yaml
- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
update nexus to latest image
see conf tests.
> 🦓 Feature/nexus 3.33.0 ubi 1 🦓

- charts/helper-sealed-secrets/Chart.yaml
- charts/helper-sealed-secrets/templates/SealedSecret.yaml
`annotation` and `labels` block moved inside if block.
`helm install ...`
> 🐎 annotation and labels moved inside if cond 🐎

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/anyuid-scc.yaml
> Fix ArgoCD Redis HA Sa permissions.

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonar-deployment.yaml
- charts/sonarqube/templates/sonarqube-admin-secret.yaml
- charts/sonarqube/templates/update-admin-pwd-hook.yaml
- charts/sonarqube/values.yaml
- update to 9.0.1-community version
- add support for admin password secret
helm install ...
> 🧸 update Sonarqube version and add support for admin secret 🧸

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
update to latest nexus ubi image 3.36.0-ubi-1
helm upgrade --install nexus redhat-cop/sonatype-nexus
> 🐑 update nexus 3.36.0 🐑

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/README.md
- charts/gitops-operator/templates/secrets.yaml
- charts/gitops-operator/values.yaml
🐱 ADD - Secrets to operator and tidy up docs 🐱
Follow the readme?
> 🐱 ADD - Secrets to operator and tidy up docs 🐱

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/secrets.yaml
> 🐵 FIX - copy error 🐵

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/argocd-cr.yaml
add missing helm hooks for AppProject when deploying into cluster with no CRD's
helm install
> 🍄 add helm hooks for appproject 🍄

- README.md
🐍 TIDY - tidy up a few bits and missing links in readme 🐍
You don't 
> 🐍 TIDY - tidy up a few bits and missing links in readme 🐍

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update default to latest argocd 2.1.8
helm install instructions
> 🧸 argocd 2.1.8 🧸

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to latest argocd and gitops operator.
have tested OK using full UJ deploy https://github.com/rht-labs/ubiquitous-journey 🦌🥳
> 🦘 v2.2.1 argocd, v1.3.2 gitops 🦘

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd to latest release
see _test and helm install. tested in TL500.
> 🪲 v2.2.2 argocd 🪲

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
What is this PR About?
update argocd to latest release
How do we test this?
see _test and helm install. tested in TL500.
> 🦎 v2.2.3 argocd 🦎

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
updates image to latest version
see tests. helm install chart.
> 🐙 update to nexus-3.37.3 🐙

- .github/workflows/conftest.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
dont lint and tests chart when only the README.md has changed
we dont do markdown llinting (yet) !
> 💣 dont lint and test on readme change 💣

- _test/conftest.sh
- charts/ipa/Chart.yaml
the releaser bug strikes again
bumping chart to get it to releas
> 🪖 ipa bump 🪖

- _test/conftest.sh
add ipa to conf tests
run conf test
> 🪖 add new ipa chart to bats 🪖

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd 2.2.6
update csv to 1.4.3
helm install
> 🦓 v2.2.6 argocd 🦓

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd v2.2.7
helm install
> 🪝 v2.2.7 argocd 🪝

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
argocd 2.3.1
check out the release blog for details on this release!
https://blog.argoproj.io/argo-cd-v2-3-release-candidate-a5b8cf11b0d3
helm install chart
> 🍔 v2.3.1 argocd 🍔

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
argocd bump to latest 2.3.3
helm install chart
> 🪛 argocd 2.3.3 🪛

- charts/ipa/Chart.yaml
- charts/ipa/setup-users.sh
- charts/ipa/values.yaml
In order to make things easier in [this section](https://rht-labs.com/tech-exercise/#/99-the-rise-of-the-cluster/1-tooling-installation) of the enablement, group name should be updated as `student`/
Install the chart as it is described in README :)
> 🐰 group name updated to comply with TL500 🐰

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to latest opernshift-gitops-operator v1.5.0
helm install
> 🐖 gitops-operator v1.5.0 🐖

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
adds the applicationset controller to the cr chart values
applicationset controller now starts when deploy this chart
helm install
> 🩲 add applicationset controller 🩲

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update default to v2.3.4 - urgent security patch fixes 
helm install
> 🐛 argocd v2.3.4 🐛

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
> Bump Gitops operator to v1.5.2

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
- charts/sonatype-nexus/values.yaml
Nexus image version updated to the latest one.
Configuration script updated to connect Nexus service address instead of route URL (cause not everyone exposes Nexus 🙈)
helm install ...
> 🐮 nexus image version updated 🐮

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to the latest patch release 2.3.5
has several security fixes - https://github.com/argoproj/argo-cd/releases/tag/v2.3.5
helm install
> 🍒 argocd v2.3.5 🍒

- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
Remove references (and urls) to a specific project...
We should keep these sorts of things as generic as possible.
> Genericize names in the Jenkins chart

- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
SonarQube version is updated
helm install..
> SonarQube Version bumped

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
> 🪺 argocd v2.3.6 🪺

- charts/ansible-automation-platform/Chart.yaml
- charts/ansible-automation-platform/values.yaml
Add AAP 2.2 channel
helm install
> Add AAP 2.2 channel

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd 2.4.9
hem install
> 🎁 argocd 2.4.9 🎁

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd 2.4.10
helm install
> ❄️ argocd 2.4.10 ❄️

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
- add python proxy for pypi
- make svc lookup more robust (lookup by label) instead of hardcoded name
helm install
> 🐍 add pypi proxy. make svc lookup more robust 🐍

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
Update to argocd 2.4.11
helm install
> 🐼 argocd 2.4.11 🐼

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
nexus pypi, POST not PUT
helm install
> 🐍 add pypi proxy. POST not a PUT 🐍

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
Reverting the changes cause I missed that I wasn't testing with the latest version :(
helm install...
> 🐷 reverting sso config 🐷

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to argocd v2.4.12
https://github.com/argoproj/argo-cd/releases/tag/v2.4.12
helm install
> 🐝 argocd v2.4.12 🐝

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
Rolling strategy does not work with persistence. The default has both so changing 
helm something something ...
> 🐨 FIX - Recreate needed for default of persistence on 🐨

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
update to latest nexus supported 3.14.1 ubi image
helm install
> 📌 nexus 3.41.1 📌

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
latest argocd release
helm install
> 🧸 argocd v2.4.14 🧸

- charts/ipa/Chart.yaml
- charts/ipa/README.md
- charts/ipa/setup-users.sh
- charts/ipa/templates/_helpers.tpl
- charts/ipa/templates/deploymentconfig.yaml
- charts/ipa/templates/route.yaml
- charts/ipa/templates/setup-oauth-job.yaml
- charts/ipa/values.yaml
Given how RHPDS is configured for the deployment of TL500, I've reverted my variable name changes to prevent a bunch of rework there. Thanks @jfilipcz for the heads up 🧑‍🍳  
helm something something?
> 🐩 REVERT - reversing the simplification of the vars 🐩

- charts/ipa/Chart.yaml
- charts/ipa/README.md
- charts/ipa/templates/clusterrolebinding.yaml
- charts/ipa/values.yaml
Continuing on the work of getting this more end to end , I've added the ldap group sync dependency and more instructions for setting it up with some dummy users for testing. 
> 🐎 ADD - Group sync for ldap  🐎

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/README.md
- charts/gitops-operator/values.yaml
update argocd to 2.4.15
helm install
> 👔 argocd v2.4.15 👔

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to latest stable argocd 2.4.17
helm install
> 💔 argocd v2.4.17 💔

- README.md
Adding openshift-logforwarding-splunk to the list of links in the top-level README
check link 
> Added openshift-logforwarding-splunk to top README

- charts/stackrox/Chart.yaml
bump chart version, unstick releaser from redme fix
> 🎈 bump, chart name is stackrox-chart, fix doc 🎈

- charts/gitops-operator/Chart.yaml
> 🌶️ argocd v2.5.4 🌶️

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
latest bug fix release argocd v.2.5.5
helm install
> 🎀 argocd v2.5.5 🎀

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
- update to argocd v2.5.7
helm install
> 🎖️ argocd v2.5.7 🎖️

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
> 🍕 argocd v2.5.9 🍕

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
Update to latest argocd v2.5.11
helm install
> 👠 argocd v2.5.11 👠

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to latest argocd v2.5.12
helm install
> 🪩 argocd v2.5.12 🪩

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to argocd v2.5.14  latest bug fix release
helm install
> 💡 argocd v2.5.14 💡

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
argocd 2.6.7 - security patch fix release
helm install
>  🌲argocd v2.6.7 🌲

- charts/ipa/Chart.yaml
- charts/ipa/templates/imagestream.yaml
- charts/ipa/values.yaml
- add newer imagestreams
- set latest fedora to fc37
- pull from quay.io to avoid docker limit 
helm install
> 🪲 add new IS, pull from quay.io 🪲

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
- update to argocd v2.7.1
no real breaking changes:
https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.6-2.7
helm install 
> 🌵 argocd v2.7.1 🌵

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
- updates to latest nexus-3.43.0-ubi-1
helm install
> 🪽 nexus-3.43.0-ubi-1 🪽

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonar-deployment.yaml
- charts/sonarqube/values.yaml
- update to latest sonarqube-9.9.1-community release
helm install
> 🦇 sonarqube 9.9.1-community 🦇

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonar-cm-copy-plugins.yaml
during testing, plugin copy script needs to point to new entrypoint/run script
e.g. add spme plugins to values.yaml to test
```
plugins:
install:
- https://github.com/checkstyle/sonar-checkstyle/releases/download/10.9.3/checkstyle-sonar-plugin-10.9.3.jar
- https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.1.0/sonar-dependency-check-plugin-3.1.0.jar
```
helm install
> 🐿️ fix sonarqube plugin start script 🐿️

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to argocd v2.7.2
helm install
> 🍄 argocd v2.7.2 🍄

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd v2.7.3
helm install
> 🦆 argocd v2.7.3 🦆

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to argocd v2.7.4
helm install
> ⛳ argocd v2.7.4 ⛳

- README.md
update readme with link to the new operators-installer chart that got missed int hat PR
click the link.
> Update README.md - add link to new operators-installer chart

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd v2.7.5
helm install
> 🦀 argocd v2.7.5 🦀

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
> 🧄 Feature/argocd 2.7.6 🧄

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
- update argocd v2.7.7.
helm install
> 🌵 argocd v2.7.7 🌵

- README.md
- charts/operators-installer/Chart.yaml
- charts/operators-installer/templates/Job_installplan-approver.yaml
- charts/operators-installer/templates/Job_installplan-complete-verifier.yaml
- charts/operators-installer/templates/Namespace.yaml
- charts/operators-installer/templates/OperatorGroup.yaml
- charts/operators-installer/templates/RoleBinding_installplan-approvers.yaml
- charts/operators-installer/templates/Role_installplan-approver.yaml
- charts/operators-installer/templates/ServiceAccount_installplan-approver.yaml
- charts/operators-installer/templates/Subscription.yaml
* fix argo sync waves so that everything in this chart happens before sync wave 0 iv not using post hooks
* updates README to have link to this chart
* increase default timeout for approve and verifier based on experimentation
see https://github.com/redhat-cop/helm-charts/pull/349 that has RFE for CI which also is based ontop of these changes.
> operators installer argo sync fixes

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
udpates default to argocd v2.7.8
helm install
> 🥀 argocd v2.7.8 🥀

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd to v2.7.10
helm install
> 🪓 argocd v2.7.10 🪓

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
> 🐾 argocd v2.7.13 🐾

- charts-we-like.md
Small change do to change of the `values.yamk` definition on sealed secrets upstream chart
ya don't, I did it for you 😘 
> 🕊️ FIX - new naming convention on chart 🕊️

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/argocd-cr.yaml
AppProject still v1alpha1 - not graduated to v1beta1 like ArgoCD
helm install
> 🌶️ Feature/argocd 2.8.3 fix 🌶️

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to latest argocd 2.8.6
helm install
> 🎲 argocd 2.8.6 🎲

- charts/operators-installer/README.md
Updates README operators-install
> Updates README operators-install

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update argocd to latest 2.9.3
helm install
> 🤿 argocd 2.9.3 🤿

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/buildconfigs.yaml
master -> replaced by main in cotainers-quickstarts
helm install
> 🪿 default to main for containers-quickstarts🪿

- charts/ipa/Chart.yaml
- charts/ipa/values.yaml
sha has been removed recently (no idea why?) so pointing to the tag instead
helm install...
> 🐢 tag updated 🐢

- charts/ipa/Chart.yaml
> 😒update chart version

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to latest argocd supported by operator
helm install
> 🦄 argocd 2.9.5 🦄

- _test/ct-config.yaml
> added update-clusterversion to excluded tests
