redhat-cop/helm-charts

- operatorhub/.helmignore
- operatorhub/Chart.yaml
- operatorhub/templates/operatorgroup.yaml
- operatorhub/templates/subscription.yaml
- operatorhub/values.yaml
Initial chart for operatorhub components (subscription, operatorgroup) that we'll be able to use to bring in different sets of operators (opendatahub, codeready workspaces, etc.)
> Add initial OperatorHub chart

- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
OpenShift has an issue .... 
When we create a `bc` with `contextDir: ''` it removes it once it's applied. this causes argo to have hiss at us. Setting it to just `/` retains the  `contextDir` and makes argo happy
> 🛁 Fix/jenkins context argo sync

- charts/bootstrap-project/Chart.yaml
- charts/bootstrap-project/templates/bindings.yaml
Fixes: https://github.com/rht-labs/helm-charts/issues/25
```
namespaces:
- name: bob
serviceaccounts:
```
Which gives:
```
---
apiVersion: v1
kind: Namespace
metadata:
name: "bob"
```
> Added check for empty bindings for bootstrap-project

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/buildconfigs.yaml
- charts/jenkins/values.yaml
Since openshift 3x jenkins imagestream points to `registry.redhat.io/openshift3/jenkins-2-rhel7`,  updated buildconfig and values to point as `quay.io/openshift/origin-jenkins` 
(Jenkins templates should be a bit tidy up later on I think 🙈)
> 🙊 jenkins image updated as quay.io 🙊

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
when job runs to configure, it should exit on timeout, not continue
increased timeout for initial pull
> 🦙exit config on timeout 🦙

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/argocd-operator/values.yaml
Route parts are changed like it is shown in the argocd-operator spec example: 
https://github.com/argoproj-labs/argocd-operator/blob/master/examples/argocd-route.yaml
> 👨‍💻fix argocd routes🔨

- .github/workflows/lint-test.yaml
Kind install is always failing for charts that require OCP features, or need PV/PVC's as two obvious examples.
This holds up the automatic releasing of minor chart changes.
We need a better way to test chart install.
Ideally this step just does what it says on the tin "linting"
> 🦜just do a lint. the kind install invariably fails 🦜

- index.html
Removes unnecessary image from gh-pages. 
Resolves #78 
@redhat-cop/day-in-the-life @springdo
> Remove image from index

- README.md
- charts-we-like.md
Starting point for adding how people can include charts they've used before but *not* the chart. Ie some upstream stuff.... 
@tylerauerbeck i know you're interested in this too
> 🧪 ADD - Collection of charts used in UJ as docs for others to see 🏂

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/imagestreams.yaml
- charts/jenkins/values.yaml
matches with master branch, jenkins agent rename. 
can switch to tagged version once stable upstream.
> 🐪 switch to agent naming 🐪

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
The initial repositories for the argo pointed at the old rht-labs.github.io/helm-charts which caused the [Ubiquitous Journey](https://github.com/rht-labs/ubiquitous-journey) to fail to deploy.
> Fix ArgoCD initial repositories to point to correct location for charts

- .github/workflows/release.yaml
As the action uses helm v3.4 (it pulls latest every time) this error is preventing our releases from happening 
https://helm.sh/blog/new-location-stable-incubator-charts/
> 🏄‍♀️ FIX - new helm repo urls 🦄

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
There was an issue with deploying the sonatype-nexus chart using `helm template redhat-cop/sonatype-nexus --version 0.0.5 --set=nameOverride=nexus --set=fullnameOverride=nexus | oc apply -f-` as the configure job which is run fails because the app label was incorrect. 
This PR variablises the app label to enable the configure job to work when the label is not `app: sonatype-nexus`.
The `nexus.name` variable doesn't seem to be picked up from the `_helpers.tpl` file so I've just used the same defaulting. If anyone with more helm knowledge knows any better way to do this I'll be happy to change.
> Fix to Nexus deploy naming

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
bump to latest stable argocd 1.8.1 release
have tested this against UJ labs bootstrap - https://github.com/rht-labs/ubiquitous-journey/pull/201/files
> 🦅 bump default to argocd 1.8.1 🦅

- charts/sonarqube/Chart.yaml
- charts/sonarqube/templates/sonar-route.yaml
At present Sonarqube only has a route on http. This sets the route the same as other apps such as Jenkins which will by default be HTTPS. If needed I can also add a variable which allows you to toggle whether this is added though that doesn't seem to be present in other places in this repo
> add tls settings to sonarqube chart

- charts/operatorhub/Chart.yaml
- charts/operatorhub/README.md
- charts/operatorhub/templates/install-modes-post-hook.yaml
- charts/operatorhub/templates/operatorgroup.yaml
- charts/operatorhub/templates/subscription.yaml
Actually this PR does two things:
* Allows the Operator to [filter more than one NS with a label Selector](https://docs.openshift.com/container-platform/4.5/operators/understanding/olm/olm-understanding-operatorgroups.html#olm-operatorgroups-target-namespace_olm-understanding-operatorgroups).
* Change the [installModes](https://docs.openshift.com/container-platform/4.5/operators/understanding/olm/olm-understanding-operatorgroups.html#olm-operatorgroups-membership_olm-understanding-operatorgroups) of the Operator. 
ping @ckavili @mvmaestri
> Allows Operator to watch more than one NS and change the installMode

- _test/prow.sh
- charts/dev-ex-dashboard/.test.sh
- charts/dev-ex-dashboard/Chart.yaml
- charts/etherpad/.test.sh
- charts/etherpad/Chart.yaml
- charts/jenkins/.test.sh
- charts/jenkins/Chart.yaml
- charts/pact-broker/.test.sh
- charts/pact-broker/Chart.yaml
- charts/sonarqube/.test.sh
- charts/sonarqube/Chart.yaml
- charts/sonatype-nexus/.test.sh
- charts/sonatype-nexus/Chart.yaml
Attempting to bring this repo under CI/automated testing.
The general idea being:
- each dir would have a `.test.sh` script, which runs helm template, test and cleanup.
- there's a `_test/prow.sh` script which runs all of them. which would be hooked up to prow, in the future.
not all charts are tested, but 70% are. https://github.com/redhat-cop/helm-charts/issues/15
_test/prow.sh
> Added test files which can be used by prow

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/config-nexus.txt
I needed to be able to change the names of the repos created in the setup script ad was also finding the raw repo wasn't being generated. I'm assuming this is because the old way is now outdated. I've used the beta rest API to create the raw hosted repo and this seems to work fine now. 
Also added the ability to define the repo names in vars `npmRepository` and `rawRepository` to match `helmRepository`. The default names for these repos match what was used before so there should be no breaking changes.
> Create static repo through beta rest api and make repo names from vars

- charts/bootstrap-project/Chart.yaml
- charts/bootstrap-project/README.md
- charts/bootstrap-project/templates/namespace.yaml
This enables adding labels to namespaces.
Only makes a change to current charts outputs if the `namespaces.*.labels` value is set.
> Ability to add labels to namespaces

- charts/ploigos/Chart.yaml
- charts/ploigos/templates/crd-reader.yaml
- charts/ploigos/templates/delete-csv-hook-rbac.yaml
- charts/ploigos/templates/delete-csv-hook.yaml
- charts/ploigos/templates/wait-for-crd.yaml
add hook-failed to deletion so resources removed on failure
help with a rerun
also worth noting the '--no-hooks' cli switch can be handy sometimes:
```
helm uninstall ploigos --no-hooks
```
> 🦤 tidy up hook deletion on failure 🦤

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/README.md
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/argocd-operator/templates/crd-reader.yaml
- charts/argocd-operator/templates/delete-csv-hook-rbac.yaml
- charts/argocd-operator/templates/delete-csv-hook.yaml
- charts/argocd-operator/templates/wait-for-crd.yaml
- charts/argocd-operator/values.yaml
this fixes the race condition when installing argocd into an empty cluster using helm lifecycle hooks, waiting for CRD to be made available by subscription/OLM
the ramifications are that 'helm template' does not recognise these hooks, this will affect https://github.com/rht-labs/ubiquitous-journey usage e.g. bootstrap would look like this
```
helm upgrade --install bootstrap -f bootstrap/values-bootstrap.yaml bootstrap --create-namespace --namespace labs-bootstrap
helm delete bootstrap --namespace labs-bootstrap --debug
```
> 🦩 argocd - fix CRD race condition 🦩

- charts/jenkins/Chart.yaml
- charts/jenkins/values.yaml
since we now have a much cleaner graal/mandrel java image introduced here - https://github.com/redhat-cop/containers-quickstarts/pull/437
we can now put back the default mvn and graal agent images in the jenkins chart
the previous mvn agent build was put in place, whilst ubi and mvn3.6+ shuffle upstream merged
> 🍩 cleanup mvn, graal agent images 🍩

- charts-we-like.md
in the process of migrating the containers-quickstarts/eap chart over to here, i found that the engineers have created one, so have doc'ed that instead in the charts-we-like, instead of pulling in the chart
- https://github.com/redhat-cop/containers-quickstarts/issues/472
> added eap example to charts-we-like

- _test/prow.sh
- charts/argocd-operator/.test.sh
- charts/bootstrap-project/.test.sh
- charts/dev-ex-dashboard/.test.sh
- charts/helper-console-links/.test.sh
- charts/jenkins/.test.sh
- charts/network-policy/.test.sh
- charts/pact-broker/.test.sh
- charts/ploigos/.test.sh
- charts/sonatype-nexus/.test.sh
added more scripts to install/test/cleanup charts on an OCP cluster
run `_test/prow.sh` against a cluster
> added more .test.sh scripts for charts

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
- charts/sonatype-nexus/values.yaml
Support a List of helm chart repos to create.
This is similar to -stable and -incubator repos in the docs:
https://helm.sh/blog/new-location-stable-incubator-charts
and supports common use cases for deploying charts to different nexus helm chart repos (-dev, -test, -staging)
Tested using helm template into new namespace
```
helm template foo . | oc apply -f-
```
> 🥝 support a list of helm chart repos 🥝

- .github/workflows/release.yaml
This PR updates the chart release workflow to use the up-to-date version of the chart-releaser action (and now uses a `setup-helm` action to allow us to specify a version of helm vs just using the latest)
You can see the results of the PR working in my branch here: https://github.com/tylerauerbeck/charts-3/runs/2328830798?check_suite_focus=true
> Update chart-releaser action version and workflow

- _test/conftest.sh
- charts/kopf/.helmignore
- charts/kopf/.test.sh
- charts/kopf/Chart.yaml
- charts/kopf/templates/clusterkopfpeering.yaml
- charts/kopf/templates/kopfpeering.yaml
- charts/kopf/values.yaml
This adds a chart that deploys the CRDs for https://github.com/nolar/kopf . It provides the ability to deploy both or only one of kopfpeering/clusterkopfpeering depending on your need.
`helm template .` 
cc: @redhat-cop/day-in-the-life @jkupferer
> Add kopf crd chart

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/README.md
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/argocd-operator/templates/Secret.yaml
- charts/argocd-operator/values.yaml
This PR is to rewrite how we are passing values to the ArgoCD custom resource used to configure an instance of the server. At the moment, our helm chart is very inflexible and requires the template to be written such that it accepts things we want to configure. Im proposing we just take anything specified in the values file under the `argocd_cr`  property and apply it to teh `ArgoCD` CR spec. This will future proof the helm chart so when new features arrive in the operator, we're not back porting them to our template of the `ArgoCD` CR
This is a breaking change so would be good to get some input from @eformat @ckavili and anyone else who uses this chart as much as we do. 
`helm install my -f values.yaml . --dry-run …
> 🐐 ADD - new approach to ArgoCD CR values 🐐

- .github/dependabot.yaml
- .github/workflows/conftest.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
This PR configures Dependabot to also watch GH Actions and allows it to open a PR if we're using old versions of Actions. It also tells existing actions to ignore a PR if things under the .github directory are changed. Some tuning may be required here, but we likely don't want all of our workflows triggering if we're just making changes to a workflow. 
Nothing to test. After merge, this will begin to watch the repo for out of date actions. This can be seen here: tylerauerbeck/charts-3#1
> Add dependabot for github actions

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
default argocd cr version was moved/brokenin #150, fix it 
deploy chart, check argocd version latest 1.8.7
> 🪅 fix cr version broken in  #150 🪅

- charts/sonarqube/Chart.yaml
- charts/sonarqube/README.md
- charts/sonarqube/templates/update-admin-pwd-hook.yaml
- charts/sonarqube/values.yaml
- update to community 8.9.0 release
- add hook for setting admin password as part of chart install
tested ok using
```
helm template charts/sonarqube --set account.adminPassword=admin123 --set account.currentAdminPassword=admin
```
> 🐍 add hook for setting admin pwd on install and update version 🐍

- .github/workflows/release.yaml
Add serial concurrency for chart releases.
Had a situation where multiple merge at same time, caused chart index.yaml to be out of date:
https://github.com/redhat-cop/helm-charts/commit/aa6ed0ea74189d8b12e89b78dd6970a6b3a03dc4
concurrency doc here:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
Should see multiple merges at similar time wait for the "staging_environment" (this is an arbitrary name)
> 🪲 add serial concurency for release jobs 🪲

- charts/pact-broker/Chart.yaml
- charts/pact-broker/templates/postgres-dc.yaml
Postgres image tag is updated as `9.6` is no longer a valid tag for OpenShift v4.7
> Postgres image tag updated

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/anyuid-scc.yaml
- charts/argocd-operator/values.yaml
According to the [documentation](https://argocd-operator.readthedocs.io/en/latest/usage/ha/#openshift), anyuid SCC is required for redis SA.
```bash
helm template --set argocd_cr.ha.enabled=true . ```
> 🐏 scc added for ha mode 🐏

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/Subscription.yaml
- charts/argocd-operator/values.yaml
Sometimes it is useful to be able to set the upgrade approval to Manual
on the operator subscription.
Allow setting installPlanApproval in the helm values, defaulting to Automatic. This will let users specify Manual if required.
Deploy the operator with `installPlanApproval: manual` and verify "Approval" is set to "Manual" in the Openshift console.
> Allow overriding of ArgoCD installPlanApproval

- charts/argocd-operator/values.yaml
- charts/bootstrap-project/Chart.yaml
- charts/bootstrap-project/templates/operatorgroup.yaml
- charts/bootstrap-project/values.yaml
the recent operator group bootstrap is all or nothing.
this change makes it more flexible (can set on namespace basis) when you bootstrap.
we only set OG in dev/test namespaces, not ci-cd in default config
```
helm template charts/bootstrap-project/ | grep -C 5 OperatorGroup
```
> 🐾 add operator group per project 🐾

- charts/argocd-operator/values.yaml
- charts/helper-sealed-secrets/Chart.yaml
- charts/helper-sealed-secrets/templates/SealedSecret.yaml
add annotation support for sealed secrets
e.g. for both tekton and jenkins we use
```
metadata:
annotations:
tekton.dev/git-0: http://gitlab-ce.gitlab.svc.cluster.local
labels:
credential.sync.jenkins.openshift.io: "true"
```
add annotations to the app-of-apps e.g.
```
- name: sealed-secrets
enabled: false
source: https://redhat-cop.github.io/helm-charts
chart_name: helper-sealed-secrets
source_ref: "1.0.2"
values:
secrets:
- name: git-auth
type: kubernetes.io/basic-auth
annotations:
tekton.dev/git-0: http://gitlab-ce.gitlab-gitlab.svc.cluster.local
labels:
credential.sync.jenkins.openshift.io: "true"
data:
username: <YOUR_SEALED_SECRET_USERNAME>
password: <YOUR_SEALED_SECRET_PASSWORD>
```
> 🔐 Feature/sealed secret helper annotations 🔐

- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/templates/imagestreams.yaml
The latest version of OpenShift Jenkins Sync Plugin doesn't discover agents with `role: jenkins-agent` but works with `role: jenkins-slave` at the moment. Therefore value of `role` label is parameterized. 
> 🐕 role value for Jenkins Agent IS updated as optional 🐕

- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/templates/imagestreams.yaml
- charts/jenkins/values.yaml
Jenkins should be ephemeral by default as all the configs are driven as IaC via https://github.com/rht-labs/s2i-config-jenkins and Jenkinsfile.  Persistent volume configs can be enabled as described in README and values file.
`helm install...`
> Jenkins chart updated to be ephemeral by default values

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/wait-for-crd.yaml
- charts/argocd-operator/values.yaml
- update to latest argocd release 2.1.0
- cluster-check hook updated delete policy to be more reliable during upgrade - avoid errors like this:
```
Error: UPGRADE FAILED: post-upgrade hooks failed: warning: Hook post-upgrade argocd-operator/templates/wait-for-crd.yaml failed: pods "cluster-check" already exists
```
Please don't merge this yet. It needs - this to merge first.
https://github.com/argoproj-labs/argocd-operator/pull/399
> 🐧 argo 2.1.2 🐧

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/anyuid-scc.yaml
As per https://github.com/redhat-cop/helm-charts/pull/191/files#r704790946
This PR reverts the service account name in the clusterrolebinding to use {{ .Values.name }} instead of .namespace
> Fix argocd-redis-ha service account name

- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/templates/ArgoCD.yaml
- charts/argocd-operator/templates/ClusterRole.yaml
- charts/argocd-operator/templates/ClusterRoleBinding.yaml
- charts/argocd-operator/templates/OperatorGroup.yaml
- charts/argocd-operator/templates/PrometheusSubscription.yaml
- charts/argocd-operator/templates/Secret.yaml
- charts/argocd-operator/templates/Subscription.yaml
- charts/argocd-operator/templates/anyuid-scc.yaml
- charts/argocd-operator/templates/crd-reader.yaml
- charts/argocd-operator/templates/helpers.tpl
- charts/argocd-operator/templates/wait-for-crd.yaml
- charts/argocd-operator/values.yaml
looks like some of the properties in the CRD for argocd have been sunset causing breaking changes. I also moved the namespace from a variable to a release or optionally passed as a var. This was to make it easier when installing.. no more double setting the ns like we used to  `--namespace my-ci-cd --create-namespace --set namespace=my-ci-cd`
helm install ....
> 🐶 FIX - Broken variables in CRD. Secret location. Proper Release naming 🐶

- _test/conftest.sh
- charts/gitops-operator/.helmignore
- charts/gitops-operator/.test.sh
- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/README.md
- charts/gitops-operator/templates/argocd-application-controller-clusterrole.yaml
- charts/gitops-operator/templates/argocd-application-controller-clusterrolebinding.yaml
- charts/gitops-operator/templates/argocd-cr.yaml
- charts/gitops-operator/templates/argocd-server-clusterrole.yaml
- charts/gitops-operator/templates/argocd-server-clusterrolebinding.yaml
- charts/gitops-operator/templates/crd-reader.yaml
- charts/gitops-operator/templates/subscription.yaml
- charts/gitops-operator/templates/wait-for-crd.yaml
- charts/gitops-operator/values.yaml
Helm chart for Red Hat GitOps Operator. Can deploy ArgoCD instances to multiple namespaces.
See README.md for more details. Contains RBAC similar to the Community ArgoCD chart (cluster admin).
test.sh
```
helm upgrade --install argocd charts/gitops-operator --create-namespace --namespace labs-ci-cd
```
> 🦑 add gitops-operator chart🦑

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/argocd-server-clusterrole.yaml
When deploying ArgoCD using the GitOps operator, the created cluster role should contain `-gitops-` in the name since the cluster role binding references <ns>-gitops-argocd-server. Without this, the ClusterRole `<ns>-argocd-server` is created but not bound.
ClusterRoleBinding in helm template:
https://github.com/redhat-cop/helm-charts/blob/gitops-operator-0.1.2/charts/gitops-operator/templates/argocd-server-clusterrolebinding.yaml#L15
This fixes the error after operator deployment when checking the sync status of a resource in the ArgoCD UI.
`
Unable to load data: events is forbidden: User "system:serviceaccount:<ns>:argocd-argocd-server" cannot list resource "events" in API group "" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "<ns>-gitops-argocd-server" not found
` …
> Fix ArgoCD server cluster role name

- charts/sonarqube/Chart.yaml
- charts/sonarqube/values.yaml
update to latest 9.2.4-community which does not have log4jshell vuln:
helm install
> 🩴 9.2.4-community 🩴

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to security patch argocd 2.2.4 release.
- https://github.com/argoproj/argo-cd/security/advisories/GHSA-63qx-x74g-jcr7
updated to latest gitops-operator csv version v1.4.1
helm installed chart OK into 4.9.17 cluster
> 🫑 v2.2.4 argocd 🫑

- charts/argocd-operator/README.md
add deprecated warning for argocd-operator-chart
we have switched over to the functionally equivalent (and supported if you have a subscription) gitops-operator chart instead.
> 🍖 add deprecated warning for argocd-operator-chart 🍖

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to lateset argocd 2.2.5 release.
fixes a nit introduced in previous security bug fix release.
helm installed chart OK into 4.9.17 cluster
> 🩹 v2.2.5 argocd 🩹

- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
- charts/jenkins/templates/configuration-as-code-configmap.yaml
- charts/jenkins/templates/deploymentconfig.yaml
- charts/jenkins/values.yaml
This PR allows users of Jenkins on Kubernetes to leverage the Configuration-as-Code plugin to configure the
CI platform in a declarative manner. This is an alternative to using the `init.groovy.d` and is far less complex. The example in the `values.yaml` shows how to seed multibranch pipelines using the Gitea plugin. 
1. Install Jenkins using the chart as an Ephemeral instance and without the Configuration-as-Code enabled
2. From the Jenkins Web Console, configure things like Gitea/SonarQube/etc...
3. Navigate to the "Manage Jenkins" section and to "Configuration as Code"
4. View the configuration
5. Select sections of the YAML corresponding to your manually configured settings and copy them to the Helm chart's values
6. Update the Helm chart with the new settings
7. You should notice …
> Added ability to use configuration-as-code on start of Jenkins

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/README.md
- charts/gitops-operator/templates/argocd-application-controller-clusterrole.yaml
- charts/gitops-operator/templates/argocd-application-controller-clusterrolebinding.yaml
- charts/gitops-operator/templates/argocd-server-clusterrole.yaml
- charts/gitops-operator/templates/argocd-server-clusterrolebinding.yaml
- charts/gitops-operator/templates/subscription.yaml
- charts/gitops-operator/values.yaml
Allow more customization of the team ArgoCD RBAC via the helm chart.
1. Add a new variable `teamInstancesAreClusterScoped` - default is true. 
this is the current behaviour of the chart today. if set to false, the extra Cluster RBAC is *not* added to team instances (so they get their RBAC from the gitops-operator only and are in namespace mode).
2. Allow Cluster RBAC for team instances to be overridden.
override the Role rules by setting one or both of these:
`clusterRoleRulesController`
`clusterRoleRulesServer`
this allows fine grained control over the RBAC. the defaults remain the same see these files:
`argocd-server-clusterrole.yaml`
`argocd-application-controller-clusterrole.yaml`
these are wider (intentionally) than what the gitops-operator set as default.
i'm working on …
> 🦕 add custom rbac and team cluster scoped 🦕

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
security fix release bump operator to v1.4.5 as default. skip broken 1.4.4
helm install
> 🦒 bump operator v1.4.5 🦒

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/README.md
- charts/sonatype-nexus/templates/config-nexus.txt
- charts/sonatype-nexus/values.yaml
- update nexus image to latest 3.38.1-ubi-1
- add support to optionally set maven-public without RedHat repositories (speed up first build if only maven-central needed)
helm install
> 🦅 update nexus to 3.38.1, make redhat mvn repos optional 🦅

- charts/operatorhub/Chart.yaml
- charts/operatorhub/values.yaml
This PR removes startingCSV field from default values.yaml file of operatorhub chart. Having that in place was effectively making that value non-optional, forcing updates to other dependant charts.
Apply the chart. If all hell doesn't break loose, all is fine! 
> [operatorhub chart] Remove startingCSV field from default values.yaml

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/secret.yaml
- charts/jenkins/values.yaml
This extends the current Jenkins chart to allow adding arbitrary annotations to the Secrets created alongside Jenkins
1. Uncomment the `annotations` in `charts/jenkins/values.yaml` for the first secret
1. Dry-run the chart `helm upgrade --install --dry-run clms-devsecops charts/jenkins/`
1. View the output and check that the secret has the expected annotations
> Allow annotations on jenkins secrets

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/templates/config-nexus.txt
make the nexus-setup job more robust. add service api check as well as the existing pod check.
we had a failure on install recently where pod was up, but api was not ready. 
helm install chart
> 🦆 make nexus setup more robust 🦆

- charts/stackrox/Chart.yaml
- charts/stackrox/templates/configure-stackrox-rbac.yaml
This PR updates the StackRox chart, adding additional permissions for ClusterRole, so the configure-stackrox job can wait for Operator Pod
N/A
> Update to Stackrox RBAC

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/subscription.yaml
- charts/gitops-operator/values.yaml
This PR makes Starting CSV optional in Subscription object for Gitops Operator
Run the chart:)
> Make Starting CSV on Gitops Operator optional

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/subscription.yaml
- charts/gitops-operator/values.yaml
This PR adds support for custom source and sourcenamespace in Gitops-operator subscription
helm template ;)
> [Gitops chart] Update Subscription template to allow for custom catalog source

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
Updates to latest argocd 2.4.7, and latest channel for gitops 1.6.0
Please read - 2.4 breaking changes argocd:
https://blog.argoproj.io/breaking-changes-in-argo-cd-2-4-29e3c2ac30c9
https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/2.3-2.4.md
https://docs.openshift.com/container-platform/4.10/cicd/gitops/gitops-release-notes.html#gitops-release-notes-1-6-0_gitops-release-notes
helm install
> 🦈 argocd 2.4.7, gitops 1.6.0 🦈

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
`.spec.dex` is deprecated, and support will be removed in Argo CD Operator v0.6.0/OpenShift GitOps v1.9.0. Dex configuration can be managed through `.spec.sso.dex` so values updated to accommodate this change.
`helm install .`
> 🐉 .spec.dex is deprecated 🐉

- charts/ipa/Chart.yaml
- charts/ipa/README.md
- charts/ipa/templates/_helpers.tpl
- charts/ipa/templates/deploymentconfig.yaml
- charts/ipa/templates/machineconfig.yaml
- charts/ipa/templates/route.yaml
- charts/ipa/templates/setup-oauth-job.yaml
- charts/ipa/values.yaml
Add infra node pinning to the chart and fixed up the dodgy OAuth patch thingy
In a cluster I ran `helm upgrade --install ipa ipa --set runOnInfra=true --set ocp_auth.enabled=true --set domain=opentlc.com --set sub_domain=springdo.sandbox1234` from the charts dir of this repo
> 🏦 UPDATE -  IPA on Infra nodes and some fixes 🏦

- charts/pact-broker/Chart.yaml
- charts/pact-broker/values.yaml
Updating the postgres image tag. In OpenShift 4.10, the imageStreamTag 9-6-el8 is not available, and therefore, the PostgreSQL pod doesn't start with the following status message: "Deployment config does not have minimum availability." by updating the image to 10-el8, the PostgreSQL DB is deployed, and the pact-broker helm chart works properly.
In your OpenShift cluster with version 4.10 or higher, do the following:
```
cd charts/pact-broker
helm install pact-broker .
```
> Updated postgres image tag (9.6-el8 not present anymore in ocp 4.10)

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to v2.5.4 argocd to match gitops-operator v1.7.0 
dex is tls enabled now (breaking change from 2.4.17)
helm install
> 🌶️ argocd v2.5.4 🌶️

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/subscription.yaml
This PR removes hardcoded namespace to be used for GitOps Operator installation. 
Run the chart
> Remove hardcoded namespace on GitOps Operator

- charts/openshift-logforwarding-splunk/Chart.yaml
- charts/openshift-logforwarding-splunk/templates/log-forwarding-splunk-certs-secret.yaml
- charts/openshift-logforwarding-splunk/templates/log-forwarding-splunk-configmap.yaml
- charts/openshift-logforwarding-splunk/templates/log-forwarding-splunk-statefulset.yaml
- charts/openshift-logforwarding-splunk/values.yaml
There are two changes in this PR, both for openshift-logforwarding-splunk:
* Added a `checksum/config` annotation to the pods in the StatefulSet to make the pods restart when the ConfigMap is updated, so the new values become active in the cluster. I used [Automatically Roll Deployments](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) from the Helm docs as inspiration.
* Replaced the optional `forwarding.splunk.caFile` value with `forwarding.splunk.ca_bundle` variable. This provides the feature to keep using the published chart and specify a custom CA bundle for connecting to the Splunk heavy forwarder with a `helm install logforwarding-splunk redhat-cop/openshift-logforwarding-splunk -f override-values-with-custom-ca-bundle.yaml`. I was not able to find …
> Accept inline splunk ca bundle

- charts/openshift-logforwarding-splunk/Chart.yaml
- charts/openshift-logforwarding-splunk/templates/log-forwarding-instance.yaml
- charts/openshift-logforwarding-splunk/values.yaml
This PR adds custom labels to the `pipelines` in the ClusterLogForwarder. The feature itself is described on https://docs.openshift.com/container-platform/4.11/logging/cluster-logging-external.html#cluster-logging-collector-log-forwarding-about_cluster-logging-external under `pipelines`. This would enable administrators to add (for example) the cluster name when forwarding logs from multiple clusters into one external logging store. 
This feature can be used by setting the labels in a custom `values.yaml` file. Default behavior has not been changed.
* `helm install` the chart, with a custom values file that sets `openshift.forwarding.[audit|app|infra].labels`.
* after installation, observe `oc get clusterlogforwarder instance -n openshift-logging -o yaml` to see the labels applied to the …
> Add custom labels to ClusterLogForwarder in openshift-logforwarding-splunk

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
-  align to new argocd v2.6.6
- see release notes:
https://docs.openshift.com/container-platform/4.12/cicd/gitops/gitops-release-notes.html
https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.5-2.6/
- sso.dex is new in config and required
- plugin config via sidecar mandatory delayed till 2.7
helm install
> 🎱 argocd v2.6.6 🎱

- charts/stackrox/Chart.yaml
- charts/stackrox/templates/configure-stackrox-job.yaml
Can occasionally get a timeout for the configure job when trying to install central e.g.
```
configure-stackrox-mnvcl configure-stackrox Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "vcentral.kb.io": failed to call webhook: Post "https://rhacs-operator-controller-manager-service.openshift-operators.svc:443/validate-platform-stackrox-io-v1alpha1-central?timeout=10s": no endpoints available for service "rhacs-operator-controller-manager-service"
``` 
Add a retry for central install.
helm install 
> 🦆 stackrox central install retry 🦆

- _test/conftest.sh
- charts/operators-installer/.helmignore
- charts/operators-installer/Chart.yaml
- charts/operators-installer/README.md
- charts/operators-installer/templates/Job_installplan-approver.yml
- charts/operators-installer/templates/Job_installplan-complete-verifier.yml
- charts/operators-installer/templates/OperatorGroup.yml
- charts/operators-installer/templates/RoleBinding_installplan-approvers.yml
- charts/operators-installer/templates/Role_installplan-approver.yml
- charts/operators-installer/templates/ServiceAccount_installplan-approver.yml
- charts/operators-installer/templates/Subscription.yml
- charts/operators-installer/templates/_helpers.tpl
- charts/operators-installer/test-install-old-operator-values.yaml
- charts/operators-installer/values.yaml
Adds `operators-installer` helm chart which allows for declarative control of managing operator versions.
Target the helm chart against a running OCP cluster.
I suggest testing with the following configs:
First
```yaml
operators:
- channel: stable
installPlanApproval: Manual
name: external-secrets-operator
source: community-operators
sourceNamespace: openshift-marketplace
csv: external-secrets-operator.v0.8.2
```
Then:
```yaml
operators:
- channel: stable
installPlanApproval: Manual
name: external-secrets-operator
source: community-operators
sourceNamespace: openshift-marketplace
csv: external-secrets-operator.v0.8.3
```
> operators-installer - init add

- charts/operators-installer/Chart.yaml
- charts/operators-installer/README.md
- charts/operators-installer/templates/Job_installplan-approver.yml
- charts/operators-installer/templates/Job_installplan-complete-verifier.yml
- charts/operators-installer/templates/OperatorGroup.yml
- charts/operators-installer/templates/RoleBinding_installplan-approvers.yml
- charts/operators-installer/templates/Role_installplan-approver.yml
- charts/operators-installer/templates/ServiceAccount_installplan-approver.yml
- charts/operators-installer/templates/Subscription.yml
- charts/operators-installer/templates/_helpers.tpl
- charts/operators-installer/test-install-old-operator-values.yaml
- charts/operators-installer/values.yaml
operators-installer
* add default helm labels to all resources
* add `commonLabels` parameter to allow user specified labels
1. `helm template foo ./charts/operators-installer -f charts/operators-installer/test-install-old-operator-values.yaml --namespace=ian-test --create-namespace | less`
2. veriy the output contains the custom label `test-label: xyz123` on all resources
> operators-installer - add default labels to all resources as well as new parameter 'commonLabels' which allows user to specify addtional labels

- charts/operators-installer/Chart.yaml
- charts/operators-installer/templates/Job_installplan-approver.yaml
- charts/operators-installer/templates/Job_installplan-complete-verifier.yaml
found case where with openshift-logging operator two installplans will get created for the same verison causing this script to mess up becasue it was assumed there would only ever be one InstallPlan for a given CSV for a given Subscription UID.
I tested this within a live environment and it resolved the issue.
> operators-installer - add handling for when more then one installplan is found for a given subscription and CSV combo

- charts/operators-installer/Chart.yaml
- charts/operators-installer/templates/Job_installplan-approver.yaml
- charts/operators-installer/templates/Job_installplan-complete-verifier.yaml
- charts/operators-installer/templates/RoleBinding_installplan-approvers.yaml
- charts/operators-installer/templates/Role_installplan-approver.yaml
- charts/operators-installer/templates/ServiceAccount_installplan-approver.yaml
fixes bug with labels that needs to be string
helm template
> operators-installer - fix label that needs to be string

- charts/operators-installer/Chart.yaml
- charts/operators-installer/ci/test-install-operator-with-long-name.yaml
- charts/operators-installer/templates/Job_installplan-approver.yaml
- charts/operators-installer/templates/Job_installplan-complete-verifier.yaml
the verifyer and approver job names can get to long, need to put in smarts to truncate them.
added a test, but actaully the test doesnt trigger the length problem because i can't find an operator thats name is to long now that i have shortnered the job name to just be "verifer" and "approver" rather then "install-plan-verifer" and "install-plan-approver" but you can run a local helm template with a made up operator name that is long and see it fail.
if anyone happens to know of an operator csv that is 54+ characters let me know.
> operators-installer - protect against job names that are to long

- charts/operators-installer/Chart.yaml
- charts/operators-installer/ci/test-install-multiple-operators-in-different-namespace-approve-via-helm-hook-values.yaml
- charts/operators-installer/ci/test-install-operator-with-channel-number.yaml
- charts/operators-installer/ci/test-install-operator-with-long-name.yaml
- charts/operators-installer/templates/Subscription.yaml
operators-installer - deal with when channel names look like numbers, but they need to string
added a new test
> operators-installer - deal with when channel names look like numbers, but they need to string

- charts/operators-installer/README.md
There was a syntax error in the code snippet `charts/operators-installer/README.md` provided for configuring custom health checks for operators.
I tested this in a local environment by installing **external-secrets-operator** with `installPlanApproval` set `Manual` and it reported the deployment as **Healthy** because of the following condition 
After the operator was deployed in Cluster using ArgoCD, `condition.type` was set to `InstallPlanPending` and `condition.status` was set to `True` without approving the **installPlan** manually.
> Fix for Syntax Error in Sample Code Snippet

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/templates/argocd-cr.yaml
- charts/gitops-operator/values.yaml
- update to argocd 2.8.3
- this matches latest gitops 2.8.2 operator default
- update to argoproj.io/v1beta1
helm install
> 🍞 argocd 2.8.3 🍞

- .github/workflows/install-test.yaml
- .github/workflows/lint-test.yaml
the automated linting and instaling testing seems to have broken. updating to the latest chart-testing-action seems to fix it.
its fixing the tests, so if the tests passed...its fixed.
> github actions - fix tests

- charts/operators-installer/Chart.yaml
- charts/operators-installer/ci/test-install-operator-subscription-with-config.yaml
- charts/operators-installer/templates/Job_installplan-approver.yaml
- charts/operators-installer/templates/Job_installplan-complete-verifier.yaml
- charts/operators-installer/templates/Subscription.yaml
- charts/operators-installer/values.yaml
Adds spec.config option to the OLM Subscription object.
Required by some operators such as [OpenShift Gitops Operator](https://developers.redhat.com/articles/2023/03/06/5-global-environment-variables-provided-openshift-gitops)
.
> Add spec.config to OLM Subscription objet

- charts/ansible-automation-platform/Chart.yaml
- charts/ansible-automation-platform/templates/AnsibleAutomationController.yaml
- charts/ansible-automation-platform/values.yaml
Added extraConfig section to support [this](https://github.com/redhat-cop/helm-charts/issues/375) so that configs like pointing to a custom DB etc can be done.
helm template .
> added extraConfig section

- .github/renovate-bump.sh
- .github/workflows/conftest.yaml
- .github/workflows/install-test.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- renovate.json
renovate PRs that change a values.yaml dont bump the chart version, so the ci fails on linting. this PR targets those PRs, by bumping the version and pushing a change to that PR.
renovate doesn't support bumping chart versions when values.yaml are changed, and the only other solution provided is for the self-hosted which we don't use.
the only weird thing about this change, is that after the commit for bumping the versions, the CI on the PR doesn't show anymore, but it is still running for the original commit from renovate. but it is slightly confusing.
**pink** is the CI running on the renovate commit.
**green** is CI being disabled by renovate, because someone else (the github action) pushed a change
> auto bump chart version when its a renovate pr

- .github/workflows/install-test.yaml
- charts/argocd-operator/Chart.yaml
- charts/argocd-operator/values.yaml
these properties are never used anywhere in the templates and renovate wants to update them, so to cut down on future pointless PRs, removing
> removed unused properties

- .github/workflows/install-test.yaml
- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecard.yml
- README.md
[scorecard ](https://github.com/ossf/scorecard) gives suggestions on how secure the repo is, that's why the actions have explicit permissions added
> added scorecard and readme badges for ci

- charts/ipa/Chart.yaml
- charts/ipa/values.yaml
default to fc39 ipa image
helm install 
> 🧨 ipa - default to fc39 image 🧨

- _test/ct-config.yaml
- charts/quay/Chart.yaml
- charts/quay/README.md
- charts/quay/templates/ns-quay-enterprise.yaml
- charts/quay/templates/quay-registry.yaml
- charts/quay/templates/secret-quay-registry-config-bundle.yaml
- charts/quay/values.yaml
Helm chart for deploying a Quay registry.
`helm install ...` (In README.md)
> 🦆 Add quay helm chart 🦆

- charts/ipa/Chart.yaml
- charts/ipa/values.yaml
IPA is not getting ready due to invalid image tag provided here, so I think we may need to update this image tag.
No manifest found for this tag: https://quay.io/repository/freeipa/freeipa-server/manifest/sha256:af20b8cf31e66db582301f40ae01d17ec05e2e54de633c8dff427410dce95894. So we should update this
> Update values.yaml to use valid free-ipa image

- renovate.json
theres been 2 PRs related to removing the digest from freeipa. the digest is added by renovate but because the upstream is rebuilding the same tag, the digest moves which causes a unknown manifest. this PR disables digest pinning for that image.
> disabled freeipa digest pinning

- charts/gitops-operator/Chart.yaml
- charts/gitops-operator/values.yaml
update to use the version that the operator default sets - currently at argocd 2.10.5
if you set the version explicitly in values.yaml - this uses the upstream image versions as before.
helm install
> 🏖️ argocd 2.10.5 🏖️

- charts/ipa/Chart.yaml
- charts/ipa/templates/machineconfig.yaml
- charts/ipa/values.yaml
When running Hosted Control Plane cluster with ipa chart in a hcp spoke - we cannot control the MachineConfig directly
so adding an enabled flag to allow this to be optional.
helm install --set machineconfig.enabled=false
> 🏖️ add MachineConfig enabled flag 🏖️

- charts/jenkins/Chart.yaml
- charts/jenkins/README.md
Fixed a broken link to containers-quickstarts
Updated formatting to pass markdownlint
Review the changes.
> Updated  jenkins/README.md

- charts/sonatype-nexus/Chart.yaml
- charts/sonatype-nexus/values.yaml
During the hands-on session of TL500 a vulnerability warning message pops up when Sonatype Nexus Repo manager is starting up
Bump the default Nexus version.
[Link to the test exercise](https://rht-labs.com/tech-exercise/#/1-the-manual-menace/4-extend-uj)
> Bump vulnerable Nexus version to 3.72.0-ubi-1

- charts/jenkins/Chart.yaml
- charts/jenkins/templates/deployment.yaml
The Deployment works just fine, was just not picking up the token.
Update your ubiquitous-journey/values-tooling.yaml:
- name: jenkins
source_ref: "jenkins-1.0.13"
> Fix: move Jenkins gitlab token outside a helm condition

- .github/workflows/install-integration-tests-operators-installer.yaml
- .github/workflows/install-unit-test.yaml
- _test/helm-install-debug-logging.sh
- charts/operators-installer/Chart.yaml
- charts/operators-installer/_scripts/installplan-approver.py
- charts/operators-installer/_scripts/installplan-incremental-approver.py
- charts/operators-installer/_scripts/installplan-verifier.py
- charts/operators-installer/_scripts/installplan_utils.py
resolves #622 
first commit allows pipelines to be manually (i can seperate this out if we must)
second commit adds in more robust and verbose logging so we could track down why the API calls were failing
then we did more testing and found that the API call was failing because we were doing an `apply` and it was cuasing the annotaitons to grow too big. in this case we really only need to do a patch so switching over to that.
the more detailed error:
```
{
"timestamp": 1743546112871,
"elapsed_time": 0.6327354907989502,
"success": false,
"status": 1,
"verb": "apply",
"cmd": [
"oc",
"apply",
"--namespace=openshift-storage",
"-f",
"-"
],
"out": "",
"err": "Warning: resource installplans/install-kwgwp is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required …
```
> issue #622 - operators-installer - need to handle when API call to approve InstallPlan fails
